using System.Collections.Generic;

namespace Baldilands;

public static class Initializer
{
    public static List<string> InitMonsters()
    {
        return new List<string>(
            new string[]
            {
                "abomination",
                "amoeba",
                "ankheg",
                "apparition",
                "archon",
                "atrocious vulture",
                "badger",
                "banshee",
                "basilisk",
                "beholder",
                "carnivorous grass",
                "carrion worm",
                "cave worm",
                "centaur",
                "cyclope",
                "dark dragon",
                "earth elemental",
                "ent",
                "gargoyle",
                "ghost",
                "giant bee",
                "giant centipede",
                "giant eagle",
                "giant grasshopper",
                "giant scorpion",
                "giant spider",
                "goblin soldier",
                "gryph",
                "gryph bee",
                "harpy",
                "hydra",
                "infernal hound",
                "jelly cube",
                "kobold guard",
                "kraken",
                "lich",
                "lion",
                "medusa",
                "mummy",
                "phoenix",
                "rattling sniffer",
                "skeleton",
                "slark",
                "smasher",
                "tarrasque",
                "tentacute",
                "tiger",
                "voracious beetle",
                "walking bush",
                "warhorse",
                "white bear",
                "wisp",
                "witch",
                "wolf",
                "wyvern",
            }
        );
    }

    public static string[] InitItems()
    {
        return new[]
        {
            "bionicsledgehammer",
            "blackbow",
            "chainmailcuirass",
            "chainmailgauntlets",
            "chainmailgreaves",
            "chainmailhelmet",
            "claymore",
            "club",
            "dwarvenwaraxe",
            "elvenbow",
            "elvencuirass",
            "elvengauntlets",
            "elvengreaves",
            "elvenhelmet",
            "furcuirass",
            "furgauntlets",
            "furgreaves",
            "furhelmet",
            "heavycrossbow",
            "ironbow",
            "ironcuirass",
            "irondagger",
            "irongauntlets",
            "irongreaves",
            "ironhelmet",
            "ironlongsword",
            "ironwaraxe",
            "leathercuirass",
            "leathergauntlets",
            "leathergreaves",
            "leatherhelmet",
            "longbow",
            "mithrilcuirass",
            "mithrilgauntlets",
            "mithrilgreaves",
            "mithrilhelmet",
            "orcishcuirass",
            "orcishgauntlets",
            "orcishgreaves",
            "orcishhelmet",
            "rustyirondagger",
            "shortbow",
            "silverlongsword",
            "steelbow",
            "steelcuirass",
            "steeldagger",
            "steelgauntlets",
            "steelgreaves",
            "steelhelmet",
            "steelmace",
            "steelwarhammer",
            "woodbow",
            "woodcuirass",
            "woodgauntlets",
            "woodgreaves",
            "woodhelmet",
            "woodsword",
            "zweihander",
        };
    }

    public static string[] Armors()
    {
        return new[]
        {
            "chainmail cuirass",
            "chainmail gauntlets",
            "chainmail greaves",
            "chainmail helmet",
            "elven cuirass",
            "elven gauntlets",
            "elven greaves",
            "elven helmet",
            "fur cuirass",
            "fur gauntlets",
            "fur greaves",
            "fur helmet",
            "iron cuirass",
            "iron gauntlets",
            "iron greaves",
            "iron helmet",
            "leather cuirass",
            "leather gauntlets",
            "leather greaves",
            "leather helmet",
            "mithril cuirass",
            "mithril gauntlets",
            "mithril greaves",
            "mithril helmet",
            "orcish cuirass",
            "orcish gauntlets",
            "orcish greaves",
            "orcish helmet",
            "steel cuirass",
            "steel gauntlets",
            "steel greaves",
            "steel helmet",
            "wood cuirass",
            "wood gauntlets",
            "wood greaves",
            "wood helmet",
        };
    }

    public static string[] Weapons()
    {
        return new[]
        {
            "bionic sledgehammer",
            "black bow",
            "claymore",
            "club",
            "dwarven war axe",
            "elven bow",
            "heavy crossbow",
            "iron bow",
            "iron dagger",
            "iron longsword",
            "iron war axe",
            "long bow",
            "rusty iron dagger",
            "short bow",
            "silver longsword",
            "steel bow",
            "steel dagger",
            "steel mace",
            "steel warhammer",
            "wood bow",
            "wood sword",
            "zweihander",
        };
    }
}
